#!/bin/bash -e

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/influxdb
  chown nobody:nogroup /var/log/influxdb

  exec chpst -u nobody:nogroup svlogd -tt /var/log/influxdb
else
  exec chpst -u nobody:nogroup regex2json "^\\s*\\[(?P<level>\\S)\\] (?P<time___time__RFC3339>\\S+?) (?P<msg>.+?)\\s*$"
fi
