#!/bin/bash -e

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/influxdb
  chown nobody:nogroup /var/log/influxdb

  exec chpst -u nobody:nogroup svlogd -tt /var/log/influxdb
else
  # TODO: Exit with 115. See: https://gitlab.com/tozd/dinit/-/issues/1
  exec chpst -u nobody:nogroup cat
fi
